export const staffPortalStyles = {
  shell: "min-h-screen bg-slate-100 font-['Poppins',sans-serif] text-slate-700",
  layout: 'flex min-h-[calc(100vh-117px)]',
  sidebar:
    'app-slider-option relative flex w-[333px] shrink-0 flex-col bg-slate-900 px-6 py-7 text-white',
  sidebarCollapsed: 'w-[58px] px-1.5 py-4',
  sidebarToggle:
    'absolute right-2 top-3 inline-flex h-7 w-7 items-center justify-center rounded-full border border-white/10 bg-white/5 text-white transition hover:bg-white/10',
  sidebarToggleIcon: 'h-3.5 w-3.5 transition-transform duration-300',
  sidebarToggleIconCollapsed: 'rotate-180',
  sidebarSections: 'mt-7 flex-1 space-y-6',
  sidebarSection: 'space-y-2.5',
  sidebarSectionTitle:
    "text-[12px] font-semibold tracking-[0.18em] text-white/70 transition-all duration-300",
  sidebarSectionTitleHidden: 'text-center text-[9px] tracking-[0.12em]',
  sidebarItems: 'space-y-2',
  sidebarItem:
    'app-slider-option flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-[15px] font-medium tracking-[0.04em] text-white/88 transition hover:bg-white/8',
  sidebarItemActive: 'bg-slate-100 text-slate-900',
  sidebarItemIcon:
    'flex h-4.5 w-4.5 shrink-0 items-center justify-center [&>svg]:h-4 [&>svg]:w-4',
  sidebarItemLabel: 'whitespace-nowrap transition-all duration-300',
  sidebarItemLabelHidden: 'w-0 overflow-hidden opacity-0',
  rolePreviewCard:
    'app-slider-option rounded-2xl bg-[#f3f2ef] p-4 text-slate-900 transition-all duration-300',
  rolePreviewCardCollapsed: 'hidden',
  rolePreviewTitle: 'text-xs font-semibold tracking-[0.14em]',
  rolePreviewText: 'mt-3 text-[11px] leading-5 text-slate-700 transition-all duration-300',
  rolePreviewTextHidden: 'h-0 overflow-hidden opacity-0',
  rolePreviewButton:
    'mt-4 w-full rounded-xl border border-slate-400 bg-slate-900 px-4 py-3 text-sm font-medium tracking-[0.04em] text-white transition',
  rolePreviewButtonCollapsed: 'px-0',
  rolePreviewButtonText: 'transition-all duration-300',
  sidebarFooter: 'mt-4 flex items-center gap-4',
  sidebarFooterAvatar: 'h-8 w-8 shrink-0 rounded-full bg-white/85',
  sidebarFooterText: 'transition-all duration-300',
  sidebarFooterTextHidden: 'w-0 overflow-hidden opacity-0',
  sidebarFooterName: 'text-[15px] font-semibold tracking-[0.06em]',
  sidebarFooterRole: "mt-1 text-[10px] tracking-[0.14em] text-white/80",
  main: 'flex-1 px-6 py-6 md:px-8',
  pageTitleRow: 'mb-6',
  pageDate: 'mb-2 text-xs font-medium uppercase tracking-[0.24em] text-slate-500',
  pageTitle: 'text-4xl font-bold text-slate-800',
  contentCard: 'rounded-2xl border border-slate-300 bg-white p-6 shadow-sm',
  contentTitle: 'text-xl font-semibold text-slate-900',
  contentText: 'mt-3 max-w-3xl text-sm leading-7 text-slate-600',
  metricsGrid: 'mt-6 grid gap-4 md:grid-cols-3',
  metricCard: 'rounded-2xl border border-slate-300 bg-white p-5 shadow-sm',
  metricLabel: 'text-sm font-medium text-slate-500',
  metricValue: 'mt-3 text-4xl font-bold text-slate-900',
} as const
